# Generated by Django 5.0.1 on 2024-04-01 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('alternative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('id_type', models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID'), ('other', 'Other')], max_length=20)),
                ('id_image', models.ImageField(upload_to='user_use')),
                ('health_issue', models.BooleanField(default=False)),
                ('health_description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
