# Generated by Django 5.0.1 on 2024-04-01 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_cmspages_package_transportation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subp_name', models.CharField(max_length=45)),
                ('sub_p_image', models.ImageField(upload_to='admin_use')),
                ('sub_p_description', models.CharField(max_length=255)),
                ('start_from', models.CharField(max_length=45)),
                ('end_place', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration_days', models.IntegerField()),
                ('cost', models.CharField(max_length=100)),
                ('cms_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.cmspages')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpackages', to='booking.package')),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.transportation')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('blood_group', models.CharField(max_length=10)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='booking.userprofile')),
                ('subpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='booking.subpackage')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_members', models.CharField(max_length=45)),
                ('cost', models.CharField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.package')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile')),
                ('subpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='booking.subpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_members', models.CharField(max_length=45)),
                ('payment_method', models.CharField(max_length=20)),
                ('booking_status', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('total_cost', models.CharField(max_length=20)),
                ('additional_booking_details', models.TextField(blank=True, null=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('updatedate', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.package')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.userprofile')),
                ('subpackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.subpackage')),
            ],
        ),
    ]
