# Generated by Django 5.0.1 on 2024-04-01 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_package_p_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='p_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
