# Generated by Django 5.0.1 on 2024-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_package_p_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='p_days',
            field=models.CharField(default='4 days & 5 Nights', max_length=45),
        ),
    ]
